/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/63NIP4hFYAd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { FormEventHandler, useEffect } from "react";
import { useForm } from "@inertiajs/react";

const locationOptions = [
  { label: "Metro Manila" },
  { label: "Luzon" },
  { label: "Visayas" },
  { label: "Mindanao" },
];

export function RegisterComponent() {
  const { data, setData, post, reset } = useForm({
    name: "",
    email: "",
    password: "",
    location: "",
    city: "",
    municipality: "",
    preferedCuisines: [],
  });

  useEffect(() => {
    return () => {
      reset();
    };
  }, []);

  const submit: FormEventHandler = (e) => {
    e.preventDefault();

    post(route("login"));
  };

  return (
    <form
      className="flex min-h-[100dvh] items-center justify-center bg-[#F0E9E5] px-4 py-12 sm:px-6 lg:px-8"
      onSubmit={submit}
    >
      <div className="mx-auto max-w-2xl w-full space-y-6 bg-white p-8 rounded-lg shadow-lg">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold tracking-tighter text-[#A38D7E] sm:text-4xl">
            Sign up to PinoyPalate
          </h1>
          <p className="text-[#7E7E7E]">
            Enter your details to create a new account.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <label
              htmlFor="name"
              className="text-sm font-medium text-[#A38D7E]"
            >
              Name
            </label>
            <input
              id="name"
              type="text"
              placeholder="John Doe"
              onChange={(e) => setData("name", e.target.value)}
              value={data.name}
              className="block w-full rounded-md border border-[#D9D1CB] bg-[#F0E9E5] px-3 py-2 text-[#7E7E7E] placeholder-[#B3B3B3] shadow-sm focus:border-[#A38D7E] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] sm:text-sm"
              required
            />
          </div>
          <div className="space-y-2">
            <label
              htmlFor="email"
              className="text-sm font-medium text-[#A38D7E]"
            >
              Email
            </label>
            <input
              id="email"
              type="email"
              placeholder="m@example.com"
              className="block w-full rounded-md border border-[#D9D1CB] bg-[#F0E9E5] px-3 py-2 text-[#7E7E7E] placeholder-[#B3B3B3] shadow-sm focus:border-[#A38D7E] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] sm:text-sm"
              required
            />
          </div>
          <div className="space-y-2">
            <label
              htmlFor="password"
              className="text-sm font-medium text-[#A38D7E]"
            >
              Password
            </label>
            <input
              id="password"
              type="password"
              placeholder="********"
              onChange={(e) =>
                setData("password", e.target.value)
              }
              value={data.password}
              className="block w-full rounded-md border border-[#D9D1CB] bg-[#F0E9E5] px-3 py-2 text-[#7E7E7E] placeholder-[#B3B3B3] shadow-sm focus:border-[#A38D7E] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] sm:text-sm"
              required
            />
          </div>
          <div className="space-y-2">
            <label
              htmlFor="location"
              className="text-sm font-medium text-[#A38D7E]"
            >
              Location
            </label>
            <select
              id="location"
              className="block w-full rounded-md border border-[#D9D1CB] bg-[#F0E9E5] px-3 py-2 text-[#7E7E7E] placeholder-[#B3B3B3] shadow-sm focus:border-[#A38D7E] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] sm:text-sm"
              required
              onChange={(e) =>
                setData("location", e.target.value)
              }
              value={data.location}
            >
              {locationOptions.map((option, index) => (
                <option key={index} value={option.label}>
                  {option.label}
                </option>
              ))}
            </select>
          </div>
          <div className="space-y-2">
            <label
              htmlFor="city"
              className="text-sm font-medium text-[#A38D7E]"
            >
              City
            </label>
            <input
              id="city"
              type="text"
              placeholder="Manila"
              onChange={(e) => setData("city", e.target.value)}
              value={data.city}
              className="block w-full rounded-md border border-[#D9D1CB] bg-[#F0E9E5] px-3 py-2 text-[#7E7E7E] placeholder-[#B3B3B3] shadow-sm focus:border-[#A38D7E] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] sm:text-sm"
              required
            />
          </div>
          <div className="space-y-2">
            <label
              htmlFor="municipality"
              className="text-sm font-medium text-[#A38D7E]"
            >
              Municipality
            </label>
            <input
              id="municipality"
              type="text"
              placeholder="Quezon City"
              onChange={(e) =>
                setData("municipality", e.target.value)
              }
              value={data.municipality}
              className="block w-full rounded-md border border-[#D9D1CB] bg-[#F0E9E5] px-3 py-2 text-[#7E7E7E] placeholder-[#B3B3B3] shadow-sm focus:border-[#A38D7E] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] sm:text-sm"
              required
            />
          </div>
        </div>
        <div className="space-y-2">
          <label className="text-sm font-medium text-[#A38D7E]">
            Preferred Cuisines
          </label>
          <div className="grid grid-cols-3 gap-2">
            <div className="flex items-center space-x-2">
              <input
                id="cuisine-savory"
                type="checkbox"
                className="h-4 w-4 rounded border-[#D9D1CB] bg-[#F0E9E5] text-[#A38D7E] focus:ring-[#A38D7E]"
              />
              <label
                htmlFor="cuisine-savory"
                className="text-[#7E7E7E]"
              >
                Savory
              </label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                id="cuisine-sweet"
                type="checkbox"
                className="h-4 w-4 rounded border-[#D9D1CB] bg-[#F0E9E5] text-[#A38D7E] focus:ring-[#A38D7E]"
              />
              <label
                htmlFor="cuisine-sweet"
                className="text-[#7E7E7E]"
              >
                Sweet
              </label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                id="cuisine-sour"
                type="checkbox"
                className="h-4 w-4 rounded border-[#D9D1CB] bg-[#F0E9E5] text-[#A38D7E] focus:ring-[#A38D7E]"
              />
              <label
                htmlFor="cuisine-sour"
                className="text-[#7E7E7E]"
              >
                Sour
              </label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                id="cuisine-bittery"
                type="checkbox"
                className="h-4 w-4 rounded border-[#D9D1CB] bg-[#F0E9E5] text-[#A38D7E] focus:ring-[#A38D7E]"
              />
              <label
                htmlFor="cuisine-bittery"
                className="text-[#7E7E7E]"
              >
                Bittery
              </label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                id="cuisine-vegan"
                type="checkbox"
                className="h-4 w-4 rounded border-[#D9D1CB] bg-[#F0E9E5] text-[#A38D7E] focus:ring-[#A38D7E]"
              />
              <label
                htmlFor="cuisine-vegan"
                className="text-[#7E7E7E]"
              >
                Vegan
              </label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                id="cuisine-bread"
                type="checkbox"
                className="h-4 w-4 rounded border-[#D9D1CB] bg-[#F0E9E5] text-[#A38D7E] focus:ring-[#A38D7E]"
              />
              <label
                htmlFor="cuisine-bread"
                className="text-[#7E7E7E]"
              >
                Bread
              </label>
            </div>
          </div>
        </div>
        <div className="flex justify-end">
          <button
            type="submit"
            className="w-full rounded-md bg-[#A38D7E] px-3 py-2 text-sm font-medium text-[#F0E9E5] shadow-sm hover:bg-[#8B7667] focus:outline-none focus:ring-1 focus:ring-[#A38D7E] disabled:cursor-not-allowed disabled:opacity-50"
          >
            Sign up
          </button>
        </div>
        <div className="text-center text-sm text-[#7E7E7E]">
          Already have an account?{" "}
          <a
            href="/login"
            className="font-medium text-[#A38D7E] hover:underline"
          >
            Sign in
          </a>
        </div>
      </div>
    </form>
  );
}
