/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QDA0HvWogWG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/Components/ui/button";

export function PinoyPalate() {
  return (
    <div className="flex flex-col min-h-dvh">
      {/* <header className="px-4 lg:px-6 h-14 flex items-center bg-[#F0E9E5]">
        <a href="#" className="flex items-center justify-center">
          <PinIcon className="size-6 text-[#A38D7E]" />
          <span className="sr-only">PinoyPalate</span>
        </a>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <a
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#A38D7E]"

          >
            Features
          </a>
          <a
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#A38D7E]"

          >
            Pricing
          </a>
          <a
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#A38D7E]"

          >
            About
          </a>
          <a
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-[#A38D7E]"

          >
            Contact
          </a>
        </nav>
      </header> */}
      {/* <section className="w-full pt-12 md:pt-24 lg:pt-32 bg-[#F0E9E5]">
        <div className="container space-y-10 xl:space-y-16">
          <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
            <div className="flex flex-col items-start space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-6xl/none text-[#A38D7E]">
                  Discover the Flavors of the Philippines
                </h1>
                <p className="max-w-[600px] text-[#7E7E7E] md:text-xl">
                  Streamline your restaurant operations and delight your customers with PinoyPalate, the ultimate
                  restaurant management app.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <a
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#A38D7E] px-8 text-sm font-medium text-[#F0E9E5] shadow transition-colors hover:bg-[#8B7667] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"

                >
                  Get Started
                </a>
                <a
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-[#A38D7E] bg-[#F0E9E5] px-8 text-sm font-medium text-[#A38D7E] shadow-sm transition-colors hover:bg-[#D9D1CB] hover:text-[#8B7667] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"

                >
                  Learn More
                </a>
              </div>
            </div>
            <div>
              <img
                src="/placeholder.svg"
                width="800"
                height="600"
                alt="Hero"
                className="mx-auto aspect-[4/3] overflow-hidden rounded-xl object-cover"
              />
            </div>
          </div>
        </div>
      </section> */}
      <section className="w-full py-12 md:py-24 lg:py-32 bg-[#F0E9E5]">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#8b5e3c]">
                Discover the Flavors of the Philippines
              </h2>
              <p className="max-w-[900px] text-[#8b5e3c] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                PinoyPalate offers a diverse menu of authentic Filipino dishes, each crafted with the finest
                ingredients and traditional cooking techniques.
              </p>
            </div>
          </div>
          <div className="mx-auto grid items-start gap-6 sm:max-w-4xl sm:grid-cols-2 md:gap-8 lg:max-w-5xl lg:grid-cols-4">
            <div className="grid gap-1">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Adobo"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
              />
              <h3 className="text-lg font-bold text-[#A38D7E]">Adobo</h3>
              <p className="text-sm text-[#7E7E7E]">
                Tender chicken or pork simmered in a savory soy sauce and vinegar marinade.
              </p>
              <div className="flex items-center justify-between">
                <Button className="bg-[#A38D7E] text-[#F0E9E5] hover:bg-[#8B7667]">Order Now</Button>
                <span className="text-lg font-bold text-[#A38D7E]">$12.99</span>
              </div>
            </div>
            <div className="grid gap-1">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Lumpia"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
              />
              <h3 className="text-lg font-bold text-[#A38D7E]">Lumpia</h3>
              <p className="text-sm text-[#7E7E7E]">
                Crispy spring rolls filled with a variety of savory ingredients.
              </p>
              <div className="flex items-center justify-between">
                <Button className="bg-[#A38D7E] text-[#F0E9E5] hover:bg-[#8B7667]">Order Now</Button>
                <span className="text-lg font-bold text-[#A38D7E]">$8.99</span>
              </div>
            </div>
            <div className="grid gap-1">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Sinigang"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
              />
              <h3 className="text-lg font-bold text-[#A38D7E]">Sinigang</h3>
              <p className="text-sm text-[#7E7E7E]">
                A tangy and savory soup made with tamarind, meat, and vegetables.
              </p>
              <div className="flex items-center justify-between">
                <Button className="bg-[#A38D7E] text-[#F0E9E5] hover:bg-[#8B7667]">Order Now</Button>
                <span className="text-lg font-bold text-[#A38D7E]">$10.99</span>
              </div>
            </div>
            <div className="grid gap-1">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Halo-Halo"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
              />
              <h3 className="text-lg font-bold text-[#A38D7E]">Halo-Halo</h3>
              <p className="text-sm text-[#7E7E7E]">
                A refreshing dessert made with shaved ice, sweetened beans, and tropical fruits.
              </p>
              <div className="flex items-center justify-between">
                <Button className="bg-[#A38D7E] text-[#F0E9E5] hover:bg-[#8B7667]">Order Now</Button>
                <span className="text-lg font-bold text-[#A38D7E]">$6.99</span>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-[#F0E9E5]">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#A38D7E]">
                What Our Customers Say
              </h2>
              <p className="max-w-[900px] text-[#7E7E7E] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hear from our satisfied customers and see how PinoyPalate has transformed their restaurant experience.
              </p>
            </div>
          </div>
          <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <div className="rounded-full w-12 h-12 bg-[#D9D1CB] flex items-center justify-center text-[#A38D7E] font-bold">
                  JD
                </div>
                <div>
                  <h4 className="text-lg font-bold text-[#A38D7E]">John Doe</h4>
                  <p className="text-sm text-[#7E7E7E]">Restaurant Owner</p>
                </div>
              </div>
              <p className="text-sm text-[#7E7E7E]">
                "PinoyPalate has been a game-changer for my restaurant.\n The intuitive interface and powerful
                features have\n streamlined our operations and helped us deliver an\n exceptional dining experience to
                our customers."
              </p>
            </div>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <div className="rounded-full w-12 h-12 bg-[#D9D1CB] flex items-center justify-center text-[#A38D7E] font-bold">
                  SM
                </div>
                <div>
                  <h4 className="text-lg font-bold text-[#A38D7E]">Sarah Martinez</h4>
                  <p className="text-sm text-[#7E7E7E]">Restaurant Manager</p>
                </div>
              </div>
              <p className="text-sm text-[#7E7E7E]">
                "I was hesitant to try a new restaurant management app,\n but PinoyPalate has exceeded all my
                expectations. The\n reporting and analytics features have helped us make\n data-driven decisions that
                have boosted our profitability."
              </p>
            </div>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <div className="rounded-full w-12 h-12 bg-[#D9D1CB] flex items-center justify-center text-[#A38D7E] font-bold">
                  KT
                </div>
                <div>
                  <h4 className="text-lg font-bold text-[#A38D7E]">Kim Tan</h4>
                  <p className="text-sm text-[#7E7E7E]">Head Chef</p>
                </div>
              </div>
              <p className="text-sm text-[#7E7E7E]">
                "As a chef, I appreciate the way PinoyPalate helps us\n manage our inventory and streamline our
                kitchen operations.\n It's made our team more efficient and allowed us to focus\n on creating
                delicious Filipino dishes for our customers."
              </p>
            </div>
          </div>
        </div>
      </section>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-[#F0E9E5]">
        <p className="text-xs text-[#7E7E7E]">&copy; 2024 PinoyPalate. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <a href="#" className="text-xs hover:underline underline-offset-4 text-[#A38D7E]">
            Terms of Service
          </a>
          <a href="#" className="text-xs hover:underline underline-offset-4 text-[#A38D7E]">
            Privacy
          </a>
        </nav>
      </footer>
    </div>
  );
}

function PinIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="17" y2="22" />
      <path d="M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z" />
    </svg>
  );
}
